export const CHAT_POOL = {
  short: [
    'miss you', 'on my way', 'love you', 'good morning', 'how was it',
    'sounds good', 'almost there', 'perfect', 'same', 'be right back',
    'haha', 'ok deal', 'heading out', 'home soon', 'sleep well',
    'good night', 'running late', 'thank you', 'you up?', 'cute',
    'just saw this', 'yep', 'nice', 'absolutely', 'cannot wait',
    'thinking of you', 'so tired', 'hungry?', 'hello', 'finally',
  ],
  medium: [
    'want to try that new place for dinner?',
    'just thinking about our conversation last night',
    'how is your day going so far?',
    'do we need anything from the store?',
    'that made me think of you',
    'can we talk about something later tonight?',
    'I had the weirdest dream last night',
    'just finished that show you recommended',
    'what do you want to do this weekend?',
    'I told my coworker about us and they thought it was sweet',
    'reminder that you are wonderful',
    'check your email I sent you something',
    'should we invite them over on Saturday?',
    'the weather is so nice right now',
    'I cannot stop thinking about what you said',
    'what are you in the mood for tonight?',
    'my meeting got cancelled so I am free early',
    'did you see the thing I left on the counter?',
    'we should plan something for next month',
    'how did your thing go today?',
  ],
  long: [
    'I had the best lunch today and it reminded me of that cafe we found on vacation last summer',
    'I was telling my friend about the conversation we had and they said we sounded really in sync',
    'I know things have been hectic but I want you to know I appreciate everything you do around here',
    'I saw this couple at the park today and they reminded me of us when we first started dating',
    'I have been thinking about what we talked about and I think you were right about all of it',
    'Just wanted to say that waking up next to you this morning was the highlight of my whole week so far',
    'I found that old photo of us from the trip and it made me smile so hard my coworker asked what was funny',
    'I think we should start that thing we talked about because I really think it would be good for us',
    'Sorry I was distracted earlier I was dealing with something at work but I am fully here now',
    'I overheard the sweetest thing today and immediately wanted to come home and tell you about it',
  ],
};
