export const RESPONSE_POOL = {
  positive: [
    'I love how you always know when I need a quiet evening together.',
    'The way you laughed at dinner tonight reminded me why I fell for you.',
    'I noticed you made my coffee this morning without me asking. That meant a lot.',
    'Watching you with your friends today made me really proud to be with you.',
    'I keep thinking about what you said last night. You really see me.',
    'Today felt easy in the best way. Just being near you was enough.',
    'You have this way of making ordinary moments feel important.',
    'I felt really connected to you during our walk today.',
    'The way you held my hand during the movie made everything better.',
    'I appreciate how patient you were with me this morning.',
    'Your voice on the phone today made my whole afternoon lighter.',
    'I love that we can sit in silence and it still feels like a conversation.',
    'You asked me how I was feeling and actually waited for the real answer.',
    'Cooking together tonight felt like the best kind of teamwork.',
    'I caught myself smiling thinking about something you said yesterday.',
    'The way you remember small details about my day means more than you know.',
    'I felt safe telling you what was bothering me. Thank you for listening.',
    'You made a hard day so much better just by being you.',
    'I love how we can be silly together without any pretense.',
    'Falling asleep next to you is still my favorite part of every day.',
  ],
  neutral: [
    'We had a pretty normal day, nothing special but it was nice.',
    'I think we could try being more intentional about our evenings.',
    'We were both busy today so we did not get much time together.',
    'It was a regular day. We talked about plans for the weekend.',
    'We watched something together but I do not think either of us was fully present.',
    'I had a lot on my mind today and did not bring much energy home.',
    'We had a fine evening. Nothing stood out but nothing was wrong either.',
    'I think we are in a comfortable routine right now.',
    'We talked mostly about logistics today. Schedules, groceries, that sort of thing.',
    'I was tired and went to bed early. We will catch up tomorrow.',
    'We spent the evening doing our own things in the same room.',
    'It was one of those days where we were both just getting through it.',
    'We made plans to do something fun this weekend. Looking forward to it.',
    'I realized we have not really checked in with each other in a few days.',
    'We had dinner together but the conversation stayed pretty surface level.',
    'I wanted to talk about something but the timing did not feel right.',
    'We are both adjusting to the new schedule. It will settle eventually.',
    'Today was fine. Not great, not bad. Just a Tuesday.',
    'We laughed at something on TV. Small moment but it was nice.',
    'I think we both need a reset. Maybe this weekend.',
  ],
  negative: [
    'I felt a bit disconnected today, like we were just going through motions.',
    'I wish we had more time to actually talk instead of just logistics.',
    'Something felt off between us today and I am not sure what it was.',
    'I wanted to bring something up but I was worried about how it would land.',
    'We snapped at each other over something small. It is not about the dishes.',
    'I felt like I was not being heard when I tried to share my day.',
    'There is a distance between us lately that I do not know how to name.',
    'I went to bed feeling like we left something unresolved.',
    'I miss the way we used to check in with each other more often.',
    'Today was hard. I needed more from you and I did not know how to ask.',
    'We had a disagreement and neither of us handled it well.',
    'I felt alone even though we were in the same room.',
    'I think we are both stressed and it is coming out sideways.',
    'I keep replaying our conversation and wishing I had said it differently.',
    'We need to talk about something but I keep putting it off.',
    'I noticed I was walking on eggshells today and that is not like us.',
    'I felt dismissed when I brought up how I was feeling.',
    'We are out of sync right now. I hope we can find our way back.',
    'I am frustrated but I also know this is temporary.',
    'Today was a reminder that we have to keep showing up even when it is hard.',
  ],
};
